POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": null,
    "email": null
}








###

GET http://localhost:8080/users HTTP/1.1

###

GET http://localhost:8080/users/1 HTTP/1.1
